spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/adhere
      username: root
      password: 123456
  redis:
    password: redis_hyk
    sentinel:
      master: mymaster
      nodes: 172.16.16.37:26379,172.16.16.37:26380,172.16.16.37:26381
